language: go
go:
  - 1.11

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

install: make get-deps

script:
  - make vet
  - make lint
  - make test
  - make cover
  - make race-test
  - make build
